# This file is part of Radler.
#
# Radler is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Radler is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Radler.  If not, see <http://www.gnu.org/licenses/>.

'''
@license: GPLv3

Created on Nov, 2025

Generate one ROS2 Python node file per Python node declaration.

'''

from radler import instrumentation
from radler.astutils.tools import write_file
from radler.radlr import infos
from radler.radlr.gen_utils import qn
from radler.radlr.gen_utils.user_sources import source_node
from radler.radlr.ros.rosutils import qn_srcfile, qn_topic


# Python node template
node_py_template = '''#!/usr/bin/env python3
"""
File Generated by radler
"""

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
import sys
import os

# Import ROS2 message types
{msg_imports}

# Import user module
# Script is installed to: lib/{module}/{node_name}
# User src is installed to: lib/{module}/user_src/
_script_dir = os.path.dirname(os.path.abspath(__file__))
_user_src_path = os.path.join(_script_dir, 'user_src', '{user_path}')
sys.path.insert(0, _user_src_path)

from {user_module} import {user_class}


# Helper classes for input/output structures
class RadlIn:
    """Input structure for subscriptions"""
    def __init__(self):
{in_struct_init}

class RadlInFlags:
    """Input flags structure for subscriptions"""
    def __init__(self):
{in_flags_struct_init}

class RadlOut:
    """Output structure for publications"""
    def __init__(self):
{out_struct_init}

class RadlOutFlags:
    """Output flags structure for publications"""
    def __init__(self):
{out_flags_struct_init}


# Flag constants (matching radl_flags.h)
RADL_STALE_VALUE = 1
RADL_STALE_MBOX = 2
RADL_STALE = 3
RADL_TIMEOUT_VALUE = 16
RADL_TIMEOUT_MBOX = 32
RADL_TIMEOUT = 48


def radl_is_stale(flags):
    """Check if the stale flag is set"""
    return (flags & RADL_STALE) != 0


def radl_is_timeout(flags):
    """Check if the timeout flag is set"""
    return (flags & RADL_TIMEOUT) != 0


class {node_class_name}(Node):
    """ROS2 node wrapper for {node_name}"""
    
    def __init__(self):
        super().__init__('{node_name}')
        
        # Initialize user class
        self._node = {user_class}()
        
        # Initialize input/output structures
        self._in = RadlIn()
        self._in_flags = RadlInFlags()
        self._out = RadlOut()
        self._out_flags = RadlOutFlags()
        
        # QoS profile
        qos_profile = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            history=HistoryPolicy.KEEP_LAST,
            depth=10
        )
        
        # Initialize publishers
{pub_init}
        
        # Initialize subscribers
{sub_init}
        
        # Initialize subscription data storage
{sub_storage_init}
        
        # Initialize timeout counters
{timeout_counters_init}
        
        # Create timer for periodic execution
        period_sec = {period}
        self._timer = self.create_timer(period_sec, self.timer_callback)
        
    def timer_callback(self):
        """Periodic callback that executes the step function"""
        # Reset gathered flags
        gathered_flags = 0
        
        # Update input flags for subscriptions
{update_in_flags}
        
        # Set default flags for outputs
{set_default_out_flags}
        
        # Call user step function
        self._node.{step_method}(self._in, self._in_flags, self._out, self._out_flags)
        
        # Publish outputs
{publish_outputs}


def main(args=None):
    rclpy.init(args=args)
    node = {node_class_name}()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
'''


def python_msg_type_to_import(msg_type_name):
    """Convert ROS2 C++ message type to Python import statement
    
    Args:
        msg_type_name: C++ message type like "std_msgs::msg::String" or "my_package::msg::MyMsg"
    
    Returns:
        Python import statement like "from std_msgs.msg import String"
    """
    # Convert C++ namespace format to Python module format
    # "std_msgs::msg::String" -> ["std_msgs", "msg", "String"]
    parts = msg_type_name.split('::')
    if len(parts) >= 3:
        pkg = parts[0]
        msg_name = parts[-1]
        return f"from {pkg}.msg import {msg_name}"
    return f"# Unknown message type: {msg_type_name}"


def python_msg_short_name(msg_type_name):
    """Extract the short message name from C++ message type
    
    Args:
        msg_type_name: C++ message type like "std_msgs::msg::String" or "my_package::msg::MyMsg"
    
    Returns:
        Short message name like "String" or "MyMsg"
    """
    parts = msg_type_name.split('::')
    return parts[-1] if parts else msg_type_name


def gennode_python(node):
    """Generate a Python ROS2 node file for a Python node declaration"""
    
    nodemodule = node._qname.rootmodule()
    source = source_node(node)
    
    # Get user class info
    user_module = source['MODULE']._val
    user_class = source['CLASS']._val
    step_method = source['STEP_METHOD']._val if source['STEP_METHOD'] else 'step'
    user_path = source['PATH']._val if source['PATH'] else '.'
    
    # Compute period in seconds
    period_ns = int(node['PERIOD']._val)
    period_sec = period_ns / 1_000_000_000.0
    
    # Generate node class name
    node_class_name = node._name.capitalize() + 'Node'
    
    # Collect message imports
    msg_imports = set()
    
    # Initialize structure fields
    in_struct_init = []
    in_flags_struct_init = []
    out_struct_init = []
    out_flags_struct_init = []
    
    # Publisher initialization
    pub_init = []
    
    # Subscriber initialization and callbacks
    sub_init = []
    sub_storage_init = []
    timeout_counters_init = []
    update_in_flags = []
    
    # Output publication
    publish_outputs = []
    set_default_out_flags = []
    
    # Process publications
    for pub in node['PUBLISHES']:
        topic = pub['TOPIC']
        pub_name = pub._name
        topic_name = qn_topic(topic._qname)
        msg_type_name = topic._ros_msgtype_name
        msg_short_name = python_msg_short_name(msg_type_name)
        
        # Add message import
        msg_imports.add(python_msg_type_to_import(msg_type_name))
        
        # Initialize output structure field
        out_struct_init.append(f"        self.{pub_name} = {msg_short_name}()")
        out_flags_struct_init.append(f"        self.{pub_name} = 0")
        
        # Create publisher
        pub_init.append(f"        self._pub_{pub_name} = self.create_publisher({msg_short_name}, '{topic_name}', qos_profile)")
        
        # Set default output flags
        set_default_out_flags.append(f"        self._out_flags.{pub_name} = gathered_flags")
        
        # Publish output
        publish_outputs.append(f"        self._pub_{pub_name}.publish(self._out.{pub_name})")
    
    # Process subscriptions
    for sub in node['SUBSCRIBES']:
        topic = sub['TOPIC']
        sub_name = sub._name
        topic_name = qn_topic(topic._qname)
        msg_type_name = topic._ros_msgtype_name
        msg_short_name = python_msg_short_name(msg_type_name)
        
        # Add message import
        msg_imports.add(python_msg_type_to_import(msg_type_name))
        
        # Initialize input structure field
        in_struct_init.append(f"        self.{sub_name} = None")
        in_flags_struct_init.append(f"        self.{sub_name} = 0")
        
        # Create subscriber storage
        sub_storage_init.append(f"        self._latest_{sub_name} = {msg_short_name}()")
        sub_storage_init.append(f"        self._is_stale_{sub_name} = True")
        
        # Create subscriber with callback
        callback_name = f"_callback_{sub_name}"
        sub_init.append(f"        self._sub_{sub_name} = self.create_subscription(")
        sub_init.append(f"            {msg_short_name},")
        sub_init.append(f"            '{topic_name}',")
        sub_init.append(f"            self.{callback_name},")
        sub_init.append(f"            qos_profile)")
        sub_init.append(f"")
        sub_init.append(f"    def {callback_name}(self, msg):")
        sub_init.append(f"        self._latest_{sub_name} = msg")
        sub_init.append(f"        self._is_stale_{sub_name} = False")
        sub_init.append(f"")
        
        # Initialize timeout counter
        timeout_counters_init.append(f"        self._tc_{sub_name} = 0")
        
        # Update input flags
        update_in_flags.append(f"        self._in.{sub_name} = self._latest_{sub_name}")
        update_in_flags.append(f"        if self._is_stale_{sub_name}:")
        update_in_flags.append(f"            self._in_flags.{sub_name} |= RADL_STALE_MBOX")
        update_in_flags.append(f"            self._tc_{sub_name} += 1")
        update_in_flags.append(f"        else:")
        update_in_flags.append(f"            self._in_flags.{sub_name} = 0")
        update_in_flags.append(f"            self._tc_{sub_name} = 0")
        update_in_flags.append(f"            self._is_stale_{sub_name} = True  # Mark as stale for next iteration")
        update_in_flags.append(f"")
    
    # Default values if no pubs/subs
    if not in_struct_init:
        in_struct_init.append("        pass")
    if not in_flags_struct_init:
        in_flags_struct_init.append("        pass")
    if not out_struct_init:
        out_struct_init.append("        pass")
    if not out_flags_struct_init:
        out_flags_struct_init.append("        pass")
    if not pub_init:
        pub_init.append("        pass")
    if not sub_init:
        sub_init.append("        pass")
    if not sub_storage_init:
        sub_storage_init.append("        pass")
    if not timeout_counters_init:
        timeout_counters_init.append("        pass")
    if not update_in_flags:
        update_in_flags.append("        pass")
    if not set_default_out_flags:
        set_default_out_flags.append("        pass")
    if not publish_outputs:
        publish_outputs.append("        pass")
    
    # Build the Python file content
    content = node_py_template.format(
        node_name=node._name,
        node_class_name=node_class_name,
        module_name=nodemodule.name(),
        user_path=user_path,
        user_module=user_module,
        user_class=user_class,
        step_method=step_method,
        period=period_sec,
        msg_imports='\n'.join(sorted(msg_imports)),
        in_struct_init='\n'.join(in_struct_init),
        in_flags_struct_init='\n'.join(in_flags_struct_init),
        out_struct_init='\n'.join(out_struct_init),
        out_flags_struct_init='\n'.join(out_flags_struct_init),
        pub_init='\n'.join(pub_init),
        sub_init='\n'.join(sub_init),
        sub_storage_init='\n'.join(sub_storage_init),
        timeout_counters_init='\n'.join(timeout_counters_init),
        update_in_flags='\n'.join(update_in_flags),
        set_default_out_flags='\n'.join(set_default_out_flags),
        publish_outputs='\n'.join(publish_outputs)
    )
    
    # Write the Python file
    node_py_name = qn_srcfile(node._qname, 'radl__', '.py')
    write_file(node_py_name, content)
    
    return node_py_name

