# This file is part of Radler.
#
# Radler is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Radler is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Radler.  If not, see <http://www.gnu.org/licenses/>.

'''
Docker file generation for Radler plants.

Generates:
- Dockerfile.<node> for each node in the plant
- docker-compose.yml to orchestrate all nodes
- FastDDS configuration for multi-container discovery

@license: GPLv3
Created on Dec, 2024
'''

from pathlib import Path

from radler.astutils.tools import write_file, ensure_dir
from radler.radlr import infos
from radler.radlr.errors import log1
from radler.radlr.rast import AstVisitor, follow_links
from radler.radlr.gen_utils.user_sources import collect_all_pip_packages


# Mapping from CMAKE_MODULE names to ROS2 apt packages
# This maps common ROS package names to their apt package equivalents
CMAKE_TO_APT_PACKAGES = {
    # Standard ROS2 messages
    'sensor_msgs': 'ros-{distro}-sensor-msgs',
    'std_msgs': 'ros-{distro}-std-msgs',
    'nav_msgs': 'ros-{distro}-nav-msgs',
    'geometry_msgs': 'ros-{distro}-geometry-msgs',
    'visualization_msgs': 'ros-{distro}-visualization-msgs',
    'diagnostic_msgs': 'ros-{distro}-diagnostic-msgs',
    'trajectory_msgs': 'ros-{distro}-trajectory-msgs',
    'actionlib_msgs': 'ros-{distro}-actionlib-msgs',
    
    # Common ROS2 packages
    'mavros_msgs': 'ros-{distro}-mavros-msgs',
    'tf2': 'ros-{distro}-tf2',
    'tf2_ros': 'ros-{distro}-tf2-ros',
    'cv_bridge': 'ros-{distro}-cv-bridge',
    'image_transport': 'ros-{distro}-image-transport',
    
    # System libraries (non-ROS)
    'Curses': 'libncurses-dev',
    'OpenCV': 'libopencv-dev',
    'Eigen3': 'libeigen3-dev',
    'Boost': 'libboost-all-dev',
}


def collect_cmake_dependencies(plantinfo):
    """
    Collect all cmake_library dependencies from nodes in the plant.
    Returns a set of CMAKE_MODULE names.
    """
    cmake_deps = set()
    
    # plantinfo.nodes contains the list of node AST objects
    for node_ast in plantinfo.nodes:
        try:
            # Get the CXX block (single item, not a list)
            cxx = node_ast['CXX']
            if cxx:
                # LIB is a list of cmake_library/static_library refs
                for lib in cxx['LIB']:
                    if hasattr(lib, '_kind') and lib._kind == 'cmake_library':
                        cmake_module = lib['CMAKE_MODULE']
                        if cmake_module:
                            cmake_deps.add(cmake_module._val)
        except (AttributeError, KeyError, TypeError):
            pass
    
    return cmake_deps


def get_apt_packages(cmake_deps, ros_distro):
    """
    Convert cmake module names to apt package names.
    Only returns packages that are in our known mapping.
    Unknown packages are assumed to be custom/local and should be built from source.
    """
    apt_packages = []
    custom_deps = []
    
    for dep in cmake_deps:
        if dep in CMAKE_TO_APT_PACKAGES:
            pkg = CMAKE_TO_APT_PACKAGES[dep].format(distro=ros_distro)
            apt_packages.append(pkg)
        else:
            # Unknown packages are likely custom - don't try to apt install them
            custom_deps.append(dep)
    
    if custom_deps:
        log1(f"Note: Custom packages (must be in workspace): {custom_deps}")
    
    return sorted(set(apt_packages))


# Dockerfile template for individual nodes
DOCKERFILE_NODE_TEMPLATE = '''# Auto-generated Dockerfile for node: {node_name}
# Generated by Radler from: {source_file}
#
# Build from radler output directory (containing ros/, radlast_*/, radl_lib/):
#   docker build -f ros/{package_name}/docker/Dockerfile.{node_name} -t {package_name}/{node_name} .
# Run:
#   docker run --rm --network {package_name}_radler_net {package_name}/{node_name}

FROM ros:{ros_distro}-ros-base AS builder
{extra_deps_comment}
# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3-colcon-common-extensions \\
    python3-pip \\
    git{apt_packages_line} \\
    && rm -rf /var/lib/apt/lists/*
{pip_install_build}
# Copy all source packages into colcon workspace
# Context is the radler output directory containing ros/, radlast_*/, radl_lib/
WORKDIR /ros_ws
COPY . src/

# Build only required packages (the target package and its dependencies)
RUN . /opt/ros/{ros_distro}/setup.sh && \\
    colcon build --packages-up-to {package_name}

# Runtime stage - minimal image
FROM ros:{ros_distro}-ros-core
{runtime_deps}
# Install Python pip for runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    python3-pip \\
    && rm -rf /var/lib/apt/lists/*
{pip_install_runtime}
# Copy built packages from builder
COPY --from=builder /ros_ws/install /opt/ros_ws/install

# Environment configuration
ENV ROS_DOMAIN_ID={ros_domain_id}
ENV PYTHONUNBUFFERED=1

# Create entrypoint script
RUN echo '#!/bin/bash\\n\\
set -e\\n\\
source /opt/ros/{ros_distro}/setup.bash\\n\\
source /opt/ros_ws/install/local_setup.bash\\n\\
exec "$@"' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/opt/ros_ws/install/{package_name}/lib/{package_name}/{node_name}"]
'''

# Docker Compose service template (no static IPs - Docker handles networking)
# When using radler-build.sh: output is /output/src/, docker folder is /output/src/ros/<pkg>/docker/
# Context ../../.. goes to /output/src/ (the colcon workspace root)
COMPOSE_SERVICE_TEMPLATE = '''  {node_name}:
    <<: *radler-common
    build:
      context: ../../..
      dockerfile: ros/{package_name}/docker/Dockerfile.{node_name}
    container_name: {package_name}_{node_name}
    networks:
      - radler_net
'''

# Full docker-compose.yml template with custom network
DOCKER_COMPOSE_TEMPLATE = '''# Auto-generated docker-compose.yml for Radler plant
# Generated from: {source_file}
# Plant: {plant_name}
#
# Usage:
#   docker-compose build    # Build all node containers
#   docker-compose up       # Run all nodes
#   docker-compose up -d    # Run all nodes in background

# Custom network for Radler nodes
networks:
  radler_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: {network_subnet}

# Common settings for all Radler nodes
x-radler-common: &radler-common
  restart: unless-stopped
  environment:
    - ROS_DOMAIN_ID=${{ROS_DOMAIN_ID:-{ros_domain_id}}}

services:
{services}
'''

# FastDDS configuration for Docker container discovery
# Uses container hostnames which Docker DNS resolves
FASTDDS_CONFIG_TEMPLATE = '''<?xml version="1.0" encoding="UTF-8" ?>
<!-- Auto-generated FastDDS configuration for Radler plant -->
<!-- This enables peer discovery across Docker containers using hostnames -->
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <profiles>
        <participant profile_name="radler_participant" is_default_profile="true">
            <rtps>
                <builtin>
                    <discovery_config>
                        <discoveryProtocol>SIMPLE</discoveryProtocol>
                        <simpleEDP>
                            <PUBWRITER_SUBALIVE>true</PUBWRITER_SUBALIVE>
                            <PUBREADER_SUBALIVE>true</PUBREADER_SUBALIVE>
                        </simpleEDP>
                        <leaseDuration>
                            <sec>10</sec>
                        </leaseDuration>
                    </discovery_config>
                    <initialPeersList>
{peer_list}
                    </initialPeersList>
                </builtin>
            </rtps>
        </participant>
    </profiles>
</dds>
'''

FASTDDS_PEER_TEMPLATE = '''                        <locator>
                            <udpv4>
                                <address>{hostname}</address>
                                <port>7412</port>
                            </udpv4>
                        </locator>
'''


def node(visitor, n, d):
    """Generate Dockerfile for a single node."""
    name = str(n._name)
    
    # Find the IP for this node from its parent system
    node_ip = None
    if n in d['plantinfo']:
        system = d['plantinfo'][n].get('system')
        if system:
            system_name = str(system._name)
            node_ip = d['system_ips'].get(system_name)
    
    node_info = {
        'node_name': name,
        'package_name': d['package_name'],
        'ros_distro': d['ros_distro'],
        'ros_domain_id': d['ros_domain_id'],
        'source_file': str(infos.source_file),
        'apt_packages_line': d.get('apt_packages_line', ''),
        'extra_deps_comment': d.get('extra_deps_comment', ''),
        'runtime_deps': d.get('runtime_deps', ''),
        'pip_install_build': d.get('pip_install_build', ''),
        'pip_install_runtime': d.get('pip_install_runtime', ''),
    }
    
    # Generate the Dockerfile for this node
    dockerfile_content = DOCKERFILE_NODE_TEMPLATE.format(**node_info)
    dockerfile_path = d['docker_folder'] / f'Dockerfile.{name}'
    write_file(dockerfile_path, dockerfile_content)
    d['dockerfiles'].append(f'Dockerfile.{name}')
    
    # Add service entry for docker-compose
    service_content = COMPOSE_SERVICE_TEMPLATE.format(**node_info)
    if node_ip:
        d['node_ips'][name] = node_ip
    
    d['services'] += service_content
    d['nodes'].append(name)
    log1(f"Generated Dockerfile for node: {name}" + (f" (IP: {node_ip})" if node_ip else ""))


def linux(visitor, s, d):
    """Process a linux system definition."""
    # Get IP if specified
    try:
        ip = s['IP']._val
        d['system_ips'][str(s._name)] = ip
        d['all_ips'].append(ip)
    except (AttributeError, KeyError):
        pass
    
    visitor.node_bf(s, d)


def machine(visitor, m, d):
    """Process a machine definition."""
    visitor.node_bf(m, d)


def compute_network_subnet(ips):
    """Compute an appropriate subnet that contains all the given IPs."""
    if not ips:
        return "172.30.0.0/16"
    
    # Parse the first IP to determine the subnet
    first_ip = ips[0]
    parts = first_ip.split('.')
    if len(parts) == 4:
        # Use a subnet that's less likely to conflict with Docker defaults
        # Docker uses 172.17.x.x by default, so we offset to 172.30.x.x
        return f"172.30.{parts[2]}.0/24"
    
    return "172.30.0.0/16"


def do_pass(plantinfo, package_name, package_folder, ros_distro='jazzy', ros_domain_id=0):
    """
    Generate Docker artifacts for a plant.
    
    Args:
        plantinfo: The computed plant information from plantcompute
        package_name: Name of the ROS package
        package_folder: Path to the package folder
        ros_distro: ROS distribution name (default: jazzy)
        ros_domain_id: ROS domain ID for network isolation (default: 0)
    
    Returns:
        List of generated file paths
    """
    docker_folder = package_folder / 'docker'
    ensure_dir(docker_folder)
    
    # Collect cmake dependencies from the plant
    cmake_deps = collect_cmake_dependencies(plantinfo)
    apt_packages = get_apt_packages(cmake_deps, ros_distro)
    if cmake_deps:
        log1(f"Detected cmake dependencies: {cmake_deps}")
        log1(f"Apt packages to install: {apt_packages}")
    
    # Collect pip package dependencies from Python nodes
    pip_packages = collect_all_pip_packages(plantinfo.nodes)
    if pip_packages:
        log1(f"Detected pip packages: {pip_packages}")
    
    # Format apt package install lines for Dockerfile
    if apt_packages:
        apt_packages_line = ' \\\n    ' + ' \\\n    '.join(apt_packages)
        extra_deps_comment = f'\n# External dependencies: {", ".join(sorted(cmake_deps))}'
        # For runtime, only install ROS message packages (not -dev packages)
        runtime_pkgs = [p for p in apt_packages if not p.endswith('-dev')]
        if runtime_pkgs:
            runtime_deps = f'''
# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    {' '.join(runtime_pkgs)} \\
    && rm -rf /var/lib/apt/lists/*
'''
        else:
            runtime_deps = ''
    else:
        apt_packages_line = ''
        extra_deps_comment = ''
        runtime_deps = ''
    
    # Format pip install lines for Dockerfile
    if pip_packages:
        pip_install_line = ' '.join(f'"{pkg}"' for pkg in pip_packages)
        pip_install_build = f'''
# Install Python dependencies (from RADL pip_package declarations)
RUN pip3 install --break-system-packages {pip_install_line}
'''
        pip_install_runtime = f'''
# Install Python dependencies (from RADL pip_package declarations)
RUN pip3 install --break-system-packages {pip_install_line}
'''
    else:
        pip_install_build = ''
        pip_install_runtime = ''
    
    d = {
        'package_name': package_name,
        'package_folder': package_folder,
        'docker_folder': docker_folder,
        'ros_distro': ros_distro,
        'ros_domain_id': ros_domain_id,
        'source_file': str(infos.source_file),
        'plant_name': str(plantinfo.plant._name),
        'plantinfo': plantinfo,
        'dockerfiles': [],
        'services': '',
        'nodes': [],
        'node_ips': {},
        'system_ips': {},
        'all_ips': [],
        # Dependency info for Dockerfiles
        'apt_packages_line': apt_packages_line,
        'extra_deps_comment': extra_deps_comment,
        'runtime_deps': runtime_deps,
        # Pip package info for Dockerfiles
        'pip_install_build': pip_install_build,
        'pip_install_runtime': pip_install_runtime,
    }
    
    # Visit the plant to generate Dockerfiles for each node
    v = AstVisitor(
        {'machine': machine, 'node': node, 'linux': linux},
        onleaf=follow_links(AstVisitor.leaf_bf),
        kind='bf'
    )
    v.visit(plantinfo.plant, d)
    
    # Compute network subnet based on IPs in the plant
    network_subnet = compute_network_subnet(d['all_ips'])
    
    # Generate docker-compose.yml
    compose_content = DOCKER_COMPOSE_TEMPLATE.format(
        source_file=d['source_file'],
        plant_name=d['plant_name'],
        ros_domain_id=d['ros_domain_id'],
        network_subnet=network_subnet,
        services=d['services'],
    )
    compose_path = docker_folder / 'docker-compose.yml'
    write_file(compose_path, compose_content)
    
    # Generate FastDDS configuration for peer discovery using container hostnames
    peer_list = ""
    for node_name in d['nodes']:
        # Use Docker container names (package_name) as hostnames
        hostname = f"{package_name}_{node_name}"
        peer_list += FASTDDS_PEER_TEMPLATE.format(hostname=hostname)
    
    fastdds_content = FASTDDS_CONFIG_TEMPLATE.format(peer_list=peer_list)
    fastdds_path = docker_folder / 'fastdds.xml'
    write_file(fastdds_path, fastdds_content)
    
    # Generate a README for the docker folder
    readme_content = generate_docker_readme(d, network_subnet)
    readme_path = docker_folder / 'README.md'
    write_file(readme_path, readme_content)
    
    # Generate run instructions (for console output)
    instructions = generate_run_instructions(d, network_subnet)
    instructions_path = docker_folder / 'RUN_INSTRUCTIONS.txt'
    write_file(instructions_path, instructions)
    
    # Generate requirements.txt if there are pip packages
    generated_files = d['dockerfiles'] + ['docker-compose.yml', 'fastdds.xml', 'README.md', 'RUN_INSTRUCTIONS.txt']
    if pip_packages:
        requirements_content = "# Auto-generated requirements.txt for Radler Python nodes\n"
        requirements_content += f"# Generated from: {d['source_file']}\n"
        requirements_content += "# Install with: pip install -r requirements.txt\n\n"
        requirements_content += '\n'.join(pip_packages) + '\n'
        requirements_path = docker_folder / 'requirements.txt'
        write_file(requirements_path, requirements_content)
        generated_files.append('requirements.txt')
        log1(f"Generated requirements.txt with {len(pip_packages)} packages")
    
    log1(f"Generated Docker artifacts in: {docker_folder}")
    
    return generated_files


def generate_run_instructions(d, network_subnet):
    """Generate console-friendly run instructions with specific node names."""
    pkg = d['package_name']
    nodes = d['nodes']
    distro = d['ros_distro']
    
    # Native ros2 run commands
    native_run_cmds = '\n  '.join(f'ros2 run {pkg} {n} &' for n in nodes[:-1])
    if nodes:
        native_run_cmds += f'\n  ros2 run {pkg} {nodes[-1]}'
    
    # Docker run commands for individual containers
    docker_run_cmds = '\n  '.join(
        f'docker run --rm --network {pkg}_radler_net {pkg}/{n}'
        for n in nodes
    )
    
    return f'''
==========================================
 RADLER BUILD COMPLETE: {pkg}
==========================================

Nodes: {', '.join(nodes)}

Replace <HOST_PATH> below with your mount path (e.g., /tmp/ros_ws)

------------------------------------------
 OPTION 1: Native (requires ROS2 + colcon)
------------------------------------------

  cd <HOST_PATH>
  source /opt/ros/{distro}/setup.bash
  colcon build
  source install/local_setup.bash
  {native_run_cmds}

------------------------------------------
 OPTION 2: Docker (no ROS installation needed)
------------------------------------------

  cd <HOST_PATH>/src/ros/{pkg}/docker
  docker-compose build
  docker-compose up

Or run containers individually after build:

  {docker_run_cmds}

==========================================
'''


def generate_docker_readme(d, network_subnet):
    """Generate a README.md for the docker folder."""
    nodes_list = '\n'.join(
        f'- `{n}` ({d["node_ips"].get(n, "dynamic IP")})' 
        for n in d['nodes']
    )
    
    return f'''# Docker Deployment for {d['package_name']}

Auto-generated by Radler from `{d['source_file']}`.

## Network Configuration

- **Network**: `radler_net` (subnet: `{network_subnet}`)
- **Discovery**: FastDDS unicast peer discovery

## Nodes

{nodes_list}

## Quick Start

1. **Build the ROS packages first** (if not already built):
   ```bash
   cd ..  # Go to workspace root
   colcon build
   ```

2. **Build all Docker containers**:
   ```bash
   docker-compose build
   ```

3. **Run all nodes**:
   ```bash
   docker-compose up
   ```

   Or run in background:
   ```bash
   docker-compose up -d
   docker-compose logs -f  # Follow logs
   ```

4. **Stop all nodes**:
   ```bash
   docker-compose down
   ```

## Running Individual Nodes

You can also build and run individual nodes:

```bash
# Build a specific node
docker build -f Dockerfile.<node_name> -t {d['package_name']}/<node_name> ..

# Run a specific node (attached to the radler network)
docker run --rm --network {d['package_name']}_radler_net {d['package_name']}/<node_name>
```

## Configuration

Environment variables:
- `ROS_DOMAIN_ID`: ROS2 domain ID for network isolation (default: {d['ros_domain_id']})
- `RMW_IMPLEMENTATION`: DDS implementation (default: rmw_fastrtps_cpp)
- `FASTRTPS_DEFAULT_PROFILES_FILE`: FastDDS configuration for peer discovery

## Multi-Machine Deployment

The containers are configured with static IPs based on the `.radl` plant definition.
This enables deterministic peer discovery across containers.

For deployment across multiple physical machines:
1. Use Docker Swarm or Kubernetes with overlay networking
2. Or configure host networking with proper DDS discovery settings
'''
