# This file is part of Radler.
#
# Radler is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Radler is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Radler.  If not, see <http://www.gnu.org/licenses/>.

'''
Docker file generation for Radler plants.

Generates:
- Dockerfile.<node> for each node in the plant
- docker-compose.yml to orchestrate all nodes

@license: GPLv3
Created on Dec, 2024
'''

from pathlib import Path

from radler.astutils.nodetrees import fun_dict_of
from radler.astutils.tools import write_file, ensure_dir
from radler.radlr import infos
from radler.radlr.errors import warning, log1
from radler.radlr.rast import AstVisitor, follow_links


# Dockerfile template for individual nodes
DOCKERFILE_NODE_TEMPLATE = '''# Auto-generated Dockerfile for node: {node_name}
# Generated by Radler from: {source_file}
#
# Build: docker build -f docker/Dockerfile.{node_name} -t {package_name}/{node_name} .
# Run:   docker run --rm --network host {package_name}/{node_name}

FROM ros:{ros_distro}-ros-core

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libstdc++6 \\
    && rm -rf /var/lib/apt/lists/*

# Copy the built ROS packages
COPY install/{package_name} /opt/ros_ws/install/{package_name}
COPY install/radl_lib /opt/ros_ws/install/radl_lib

# Environment configuration
ENV ROS_DOMAIN_ID={ros_domain_id}
ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# Create entrypoint script
RUN echo '#!/bin/bash\\n\\
set -e\\n\\
source /opt/ros/{ros_distro}/setup.bash\\n\\
source /opt/ros_ws/install/{package_name}/local_setup.bash\\n\\
exec "$@"' > /entrypoint.sh && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/opt/ros_ws/install/{package_name}/lib/{package_name}/{node_name}"]
'''

# Docker Compose service template for individual nodes
COMPOSE_SERVICE_TEMPLATE = '''  {node_name}:
    <<: *radler-common
    build:
      context: ..
      dockerfile: docker/Dockerfile.{node_name}
    container_name: {package_name}_{node_name}
'''

# Docker Compose service template with SROS2 security
COMPOSE_SERVICE_SROS2_TEMPLATE = '''  {node_name}:
    <<: *radler-common
    build:
      context: ..
      dockerfile: docker/Dockerfile.{node_name}
    container_name: {package_name}_{node_name}
    volumes:
      - ./sros2_keys:/sros2_keys:ro
    environment:
      - ROS_SECURITY_KEYSTORE=/sros2_keys
      - ROS_SECURITY_ENABLE=true
      - ROS_SECURITY_STRATEGY=Enforce
    command: ["--ros-args", "--enclave", "/{package_name}/{node_name}"]
'''

# Full docker-compose.yml template
DOCKER_COMPOSE_TEMPLATE = '''# Auto-generated docker-compose.yml for Radler plant
# Generated from: {source_file}
# Plant: {plant_name}
#
# Usage:
#   docker-compose build    # Build all node containers
#   docker-compose up       # Run all nodes
#   docker-compose up -d    # Run all nodes in background

version: '3.8'

# Common settings for all Radler nodes
x-radler-common: &radler-common
  restart: unless-stopped
  network_mode: host
  environment:
    - ROS_DOMAIN_ID=${{ROS_DOMAIN_ID:-{ros_domain_id}}}
    - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

services:
{services}
'''


def node(visitor, n, d):
    """Generate Dockerfile for a single node."""
    name = str(n._name)
    
    node_info = {
        'node_name': name,
        'package_name': d['package_name'],
        'ros_distro': d['ros_distro'],
        'ros_domain_id': d['ros_domain_id'],
        'source_file': str(infos.source_file),
    }
    
    # Generate the Dockerfile for this node
    dockerfile_content = DOCKERFILE_NODE_TEMPLATE.format(**node_info)
    dockerfile_path = d['docker_folder'] / f'Dockerfile.{name}'
    write_file(dockerfile_path, dockerfile_content)
    d['dockerfiles'].append(f'Dockerfile.{name}')
    
    # Add service entry for docker-compose
    service_content = COMPOSE_SERVICE_TEMPLATE.format(**node_info)
    d['services'] += service_content
    
    d['nodes'].append(name)
    log1(f"Generated Dockerfile for node: {name}")


def linux_system(visitor, s, d):
    """Process a linux system definition."""
    # Get IP if specified
    try:
        ip = s['IP']._val
        d['system_ips'][str(s._name)] = ip
    except (AttributeError, KeyError):
        pass
    
    visitor.node_bf(s, d)


def machine(visitor, m, d):
    """Process a machine definition."""
    visitor.node_bf(m, d)


def do_pass(plantinfo, package_name, package_folder, ros_distro='jazzy', ros_domain_id=0):
    """
    Generate Docker artifacts for a plant.
    
    Args:
        plantinfo: The computed plant information from plantcompute
        package_name: Name of the ROS package
        package_folder: Path to the package folder
        ros_distro: ROS distribution name (default: jazzy)
        ros_domain_id: ROS domain ID for network isolation (default: 0)
    
    Returns:
        List of generated file paths
    """
    docker_folder = package_folder / 'docker'
    ensure_dir(docker_folder)
    
    d = {
        'package_name': package_name,
        'package_folder': package_folder,
        'docker_folder': docker_folder,
        'ros_distro': ros_distro,
        'ros_domain_id': ros_domain_id,
        'source_file': str(infos.source_file),
        'plant_name': str(plantinfo.plant._name),
        'dockerfiles': [],
        'services': '',
        'nodes': [],
        'system_ips': {},
    }
    
    # Visit the plant to generate Dockerfiles for each node
    v = AstVisitor(
        fun_dict_of((machine, node, ('linux', linux_system))),
        onleaf=follow_links(AstVisitor.leaf_bf),
        kind='bf'
    )
    v.visit(plantinfo.plant, d)
    
    # Generate docker-compose.yml
    compose_content = DOCKER_COMPOSE_TEMPLATE.format(
        source_file=d['source_file'],
        plant_name=d['plant_name'],
        ros_domain_id=d['ros_domain_id'],
        services=d['services'],
    )
    compose_path = docker_folder / 'docker-compose.yml'
    write_file(compose_path, compose_content)
    
    # Generate a README for the docker folder
    readme_content = generate_docker_readme(d)
    readme_path = docker_folder / 'README.md'
    write_file(readme_path, readme_content)
    
    log1(f"Generated Docker artifacts in: {docker_folder}")
    
    return d['dockerfiles'] + ['docker-compose.yml', 'README.md']


def generate_docker_readme(d):
    """Generate a README.md for the docker folder."""
    nodes_list = '\n'.join(f'- `{n}`' for n in d['nodes'])
    
    return f'''# Docker Deployment for {d['package_name']}

Auto-generated by Radler from `{d['source_file']}`.

## Nodes

{nodes_list}

## Quick Start

1. **Build the ROS packages first** (if not already built):
   ```bash
   cd ..  # Go to workspace root
   colcon build
   ```

2. **Build all Docker containers**:
   ```bash
   docker-compose build
   ```

3. **Run all nodes**:
   ```bash
   docker-compose up
   ```

   Or run in background:
   ```bash
   docker-compose up -d
   docker-compose logs -f  # Follow logs
   ```

4. **Stop all nodes**:
   ```bash
   docker-compose down
   ```

## Running Individual Nodes

You can also build and run individual nodes:

```bash
# Build a specific node
docker build -f Dockerfile.<node_name> -t {d['package_name']}/<node_name> ..

# Run a specific node
docker run --rm --network host {d['package_name']}/<node_name>
```

## Configuration

Environment variables:
- `ROS_DOMAIN_ID`: ROS2 domain ID for network isolation (default: {d['ros_domain_id']})
- `RMW_IMPLEMENTATION`: DDS implementation (default: rmw_fastrtps_cpp)

## Network Mode

By default, containers use `network_mode: host` to allow ROS2 DDS discovery
to work across containers. For production deployments, consider using
a dedicated Docker network with multicast support.
'''

